import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { analyzeText, assessUrl, type ScanResult } from '@safescroll/detection-core';
import { createWorker } from 'tesseract.js';
import { ImageUp, Link2, ScanText, ShieldAlert, Volume2 } from 'lucide-react';
import { localModelRisk } from '../shared/browser-local-ai';
import './styles.css';

const DEFAULT_API='http://localhost:8000';
function speak(text:string){ if('speechSynthesis' in window){speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.rate=.85; speechSynthesis.speak(u);} }
async function getApi(){const x=await chrome.storage.local.get(['apiBaseUrl']); return typeof x.apiBaseUrl==='string'&&x.apiBaseUrl?x.apiBaseUrl:DEFAULT_API;}
async function getCurrentPageText(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});const tab=tabs[0];if(!tab?.id)return '';const injected=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>document.body?.innerText?.slice(0,12000)??''});return String(injected[0]?.result??'');}
function applyLocalModel(base:ScanResult,text:string):ScanResult{const m=localModelRisk(text);if(m.probability>=.82&&base.severity!=='SCAM') return {...base,severity:'SUSPICIOUS',score:Math.max(base.score,Math.round(m.probability*100)),explanation:'The local safety model found additional scam-like language patterns. Verify before acting.'};return base;}
function App(){
 const [text,setText]=useState('');const [url,setUrl]=useState('');const [result,setResult]=useState<ScanResult|null>(null);const [busy,setBusy]=useState(false);const [ocrBusy,setOcrBusy]=useState(false);const [enhanced,setEnhanced]=useState(false);const [api,setApi]=useState(DEFAULT_API);
 useEffect(()=>{chrome.storage.session.get('safescrollLastSelection').then(v=>{if(typeof v.safescrollLastSelection==='string')setText(v.safescrollLastSelection);});getApi().then(setApi);},[]);
 const localRun=(t=text,u=url)=>{const base=analyzeText(t,u||undefined);const improved=applyLocalModel(base,t);setResult(improved);return improved;};
 const scanPage=async()=>{setBusy(true);try{const page=await getCurrentPageText();setText(page);localRun(page);}catch{setResult(null);}finally{setBusy(false);}};
 const run=async()=>{setBusy(true);try{if(enhanced){const r=await fetch(`${api}/api/v1/scan/text`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:text,url:url||undefined,enhanced:true})});if(r.ok){setResult(await r.json());return;}}localRun();}catch{localRun();}finally{setBusy(false);}};
 const runUrl=()=>{if(!url)return;const a=assessUrl(url);setResult({severity:a.score>=60?'SCAM':a.suspicious?'SUSPICIOUS':'LOW_RISK',score:a.score,category:'credential_phishing',evidence:a.reasons.map((label,i)=>({code:`url_${i}`,label,weight:8})),explanation:a.reasons.join(' ')||'No strong URL warning signals were found.',actions:['Verify the domain before entering information.','Do not sign in through unexpected links.'],language:'en',url:a});};
 const scanImage=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setOcrBusy(true);try{const worker=await createWorker('eng+ben', 1, { workerPath: chrome.runtime.getURL('tesseract/worker.min.js'), corePath: chrome.runtime.getURL('tesseract/tesseract-core.wasm.js'), langPath: chrome.runtime.getURL('tesseract') });const {data}=await worker.recognize(file);await worker.terminate();setText(data.text);localRun(data.text);}catch{setResult({severity:'SUSPICIOUS',score:35,category:'unknown',evidence:[{code:'ocr_error',label:'The screenshot could not be read reliably.',weight:10}],explanation:'We could not read this screenshot reliably. Try a clearer image.',actions:['Do not act on an unclear message.','Try scanning a clearer screenshot.'],language:'unknown'});}finally{setOcrBusy(false);e.target.value='';}};
 return <div className="app"><header><div><div className="brand">SafeScroll<span>.</span></div><div className="sub">Digital safety, made simple.</div></div><div className="local">● ZERO</div></header><main><h1>Pause before you click.</h1><p className="lead">Local rules + small AI run on this device. Enhanced AI is optional.</p><section className="card"><label>Message or page text</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste suspicious text here…"/><label>Optional URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com"/><div className="toggle"><input id="enhanced" type="checkbox" checked={enhanced} onChange={e=>setEnhanced(e.target.checked)}/><label htmlFor="enhanced">Enhanced AI — selected text may leave this device</label></div><div className="grid"><button onClick={scanPage} disabled={busy}><ScanText size={16}/>Scan current page</button><button className="secondary" onClick={run} disabled={!text||busy}><ScanText size={16}/>{busy?'Analyzing…':'Scan text'}</button><button className="secondary" onClick={runUrl} disabled={!url}><Link2 size={16}/>Check link</button></div><label className="upload"><ImageUp size={16}/>{ocrBusy?'Reading screenshot…':'Scan screenshot'}<input type="file" accept="image/*" onChange={scanImage} hidden/></label></section>{result&&<section className={`result ${result.severity.toLowerCase()}`}><div className="top"><ShieldAlert size={23}/><div><div className="eyebrow">Assessment</div><div className="severity">{result.severity.replace('_',' ')}</div></div><strong>{result.score}</strong></div><p>{result.explanation}</p><div className="chips">{result.evidence.map(e=><span key={e.code}>{e.label}</span>)}</div><div className="what"><div className="eyebrow">What to do</div>{result.actions.map(a=><div key={a}>• {a}</div>)}</div><button className="speak" onClick={()=>speak(`${result.severity}. ${result.explanation} ${result.actions.join(' ')}`)}><Volume2 size={16}/>Read aloud</button></section>}</main><footer>Local-first · user initiated · small on-device model · no raw message storage</footer></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
